export const GET_CUSTOMERS_REQUEST = 'GET_CUSTOMERS_REQUEST'
export const GET_CUSTOMERS_SUCCESS = 'GET_CUSTOMERS_SUCCESS'
export const GET_CUSTOMERS_FAILURE = 'GET_CUSTOMERS_FAILURE'

export const DELETE_CUSTOMER_REQUEST = "DELETE_CUSTOMER_REQUEST"
export const DELETE_CUSTOMER_SUCCESS = "DELETE_CUSTOMER_SUCCESS"
export const DELETE_CUSTOMER_FAILURE = "DELETE_CUSTOMER_REQUEST"

export const GET_USER_BY_ID_REQUEST = "GET_USER_BY_ID_REQUEST"
export const GET_USER_BY_ID_SUCCESS = "GET_USER_BY_ID_SUCCESS"
export const GET_USER_BY_ID_FAILURE = "GET_USER_BY_ID_FAILURE"

export const EDIT_USER_BY_ADMIN_REQUEST = "EDIT_USER_BY_ADMIN_REQUEST"
export const EDIT_USER_BY_ADMIN_SUCCESS = "EDIT_USER_BY_ADMIN_SUCCESS"
export const EDIT_USER_BY_ADMIN_FAILURE = "EDIT_USER_BY_ADMIN_FAILURE"

export const FIND_USER_BY_EMAIL_REQUEST = "FIND_USER_BY_EMAIL_REQUEST"
export const FIND_USER_BY_EMAIL_SUCCESS = "FIND_USER_BY_EMAIL_SUCCESS"
export const FIND_USER_BY_EMAIL_FAILURE = "FIND_USER_BY_EMAIL_FAILURE"
