export const GET_ORDER_REQUEST = "GET_ORDER_REQUEST"
export const GET_ORDER_SUCCESS = "GET_ORDER_SUCCESS"
export const GET_ORDER_FAILURE = "GET_ORDER_FAILURE"

export const DELETE_ORDER_REQUEST = "DELETE_ORDER_REQUEST"
export const DELETE_ORDER_SUCCESS = "DELETE_ORDER_SUCCESS"
export const DELETE_ORDER_FAILURE = "DELETE_ORDER_FAILURE"

export const PUT_ORDER_STATUS_REQUEST = "PUT_ORDER_STATUS_REQUEST"
export const PUT_ORDER_STATUS_SUCCESS = "PUT_ORDER_STATUS_SUCCESS"
export const PUT_ORDER_STATUS_FAILURE = "PUT_ORDER_STATUS_FAILURE"

export const GET_ORDER_TOP_WEEK_REQUEST = "GET_ORDER_TOP_WEEK_REQUEST"
export const GET_ORDER_TOP_WEEK_SUCCESS = "GET_ORDER_TOP_WEEK_SUCCESS"
export const GET_ORDER_TOP_WEEK_FAILURE = "GET_ORDER_TOP_WEEK_FAILURE"

export const GET_ORDER_TOP_MONTH_REQUEST = "GET_ORDER_TOP_MONTH_REQUEST"
export const GET_ORDER_TOP_MONTH_SUCCESS = "GET_ORDER_TOP_MONTH_SUCCESS"
export const GET_ORDER_TOP_MONTH_FAILURE = "GET_ORDER_TOP_MONTH_FAILURE"

export const GET_ORDER_TOP_YEAR_REQUEST = "GET_ORDER_TOP_YEAR_REQUEST"
export const GET_ORDER_TOP_YEAR_SUCCESS = "GET_ORDER_TOP_YEAR_SUCCESS"
export const GET_ORDER_TOP_YEAR_FAILURE = "GET_ORDER_TOP_YEAR_FAILURE"

export const GET_TOTAL_QUANTITY_YEAR_REQUEST = "GET_TOTAL_QUANTITY_YEAR_REQUEST"
export const GET_TOTAL_QUANTITY_YEAR_SUCCESS = "GET_TOTAL_QUANTITY_YEAR_SUCCESS"

export const GET_TOTAL_QUANTITY_YEAR_FAILURE = "GET_TOTAL_QUANTITY_YEAR_FAILURE"

export const GET_TOTAL_PRICE_YEAR_REQUEST = "GET_TOTAL_PRICE_YEAR_REQUEST"
export const GET_TOTAL_PRICE_YEAR_SUCCESS = "GET_TOTAL_PRICE_YEAR_SUCCESS"

export const GET_TOTAL_PRICE_YEAR_FAILURE = "GET_TOTAL_PRICE_YEAR_FAILURE"
