export const GET_CATEGORY_REQUEST = "GET_CATEGORY_REQUEST"
export const GET_CATEGORY_SUCCESS = "GET_CATEGORY_SUCCESS"
export const GET_CATEGORY_FAILURE = "GET_CATEGORY_FAILURE"

export const DELETE_CATEGORY_BY_ID_REQUEST = "DELETE_CATEGORY_BY_ID_REQUEST"
export const DELETE_CATEGORY_BY_ID_SUCCESS = "DELETE_CATEGORY_BY_ID_SUCCESS"
export const DELETE_CATEGORY_BY_ID_FAILURE = "DELETE_CATEGORY_BY_ID_FAILURE"

export const CREATE_CATEGORY_REQUEST = "CREATE_CATEGORY_REQUEST"
export const CREATE_CATEGORY_SUCCESS = "CREATE_CATEGORY_SUCCESS"
export const CREATE_CATEGORY_FAILURE = "CREATE_CATEGORY_FAILURE"


