export const CREATE_VOUCHER_REQUEST = "CREATE_VOUCHER_REQUEST";
export const CREATE_VOUCHER_SUCCESS = "CREATE_VOUCHER_SUCCESS";
export const CREATE_VOUCHER_FAILURE = "CREATE_VOUCHER_FAILURE";

export const GET_VOUCHER_REQUEST = "GET_VOUCHER_REQUEST"
export const GET_VOUCHER_SUCCESS = "GET_VOUCHER_SUCCESS"
export const GET_VOUCHER_FAILURE = "GET_VOUCHER_FAILURE"

export const DELETE_VOUCHER_BY_ID_REQUEST = "DELETE_VOUCHER_BY_ID_REQUEST"
export const DELETE_VOUCHER_BY_ID_SUCCESS = "DELETE_VOUCHER_BY_ID_SUCCESS"
export const DELETE_VOUCHER_BY_ID_FAILURE = "DELETE_VOUCHER_BY_ID_FAILURE"

export const FIND_VOUCHER_BY_ID_REQUEST = "FIND_VOUCHER_BY_ID_REQUEST"
export const FIND_VOUCHER_BY_ID_SUCCESS = "FIND_VOUCHER_BY_ID_SUCCESS"
export const FIND_VOUCHER_BY_ID_FAILURE = "FIND_VOUCHER_BY_ID_FAILURE"

export const CHANGE_VOUCHER_REQUEST = "CHANGE_VOUCHER_REQUEST"
export const CHANGE_VOUCHER_SUCCESS = "CHANGE_VOUCHER_SUCCESS"
export const CHANGE_VOUCHER_FAILURE = "CHANGE_VOUCHER_FAILURE"




