export const CREATE_ORDER_REQUEST = 'CREATE_ORDER_REQUEST'
export const CREATE_ORDER_SUCCESS = 'CREATE_ORDER_SUCCESS'
export const CREATE_ORDER_FAILURE = 'CREATE_ORDER_FAILURE'

export const CREATE_CHECKOUT_REQUEST = 'CREATE_CHECKOUT_REQUEST'
export const CREATE_CHECKOUT_SUCCESS = 'CREATE_CHECKOUT_SUCCESS'
export const CREATE_CHECKOUT_FAILURE = 'CREATE_CHECKOUT_FAILURE'

export const GET_ORDER_REQUEST = 'GET_ORDER_REQUEST'
export const GET_ORDER_SUCCESS = 'GET_ORDER_SUCCESS'
export const GET_ORDER_FAILURE = 'GET_ORDER_FAILURE'

export const GET_ORDER_BY_USER_REQUEST = 'GET_ORDER_BY_USER_REQUEST'
export const GET_ORDER_BY_USER_SUCCESS = 'GET_ORDER_BY_USER_SUCCESS'
export const GET_ORDER_BY_USER_FAILURE = 'GET_ORDER_BY_USER_FAILURE'

export const GET_ORDER_BY_ID_REQUEST = 'GET_ORDER_BY_ID_REQUEST'
export const GET_ORDER_BY_ID_SUCCESS = 'GET_ORDER_BY_ID_SUCCESS'
export const GET_ORDER_BY_ID_FAILURE = 'GET_ORDER_BY_ID_FAILURE'

export const GET_ORDER_HISTORY_REQUEST = 'GET_ORDER_HISTORY_REQUEST'
export const GET_ORDER_HISTORY_SUCCESS = 'GET_ORDER_HISTORY_SUCCESS'
export const GET_ORDER_HISTORY_FAILURE = 'GET_ORDER_HISTORY_FAILURE'

export const GET_ORDER_ITEM_REQUEST = "GET_ORDER_ITEM_REQUEST"
export const GET_ORDER_ITEM_SUCCESS = "GET_ORDER_ITEM_SUCCESS"
export const GET_ORDER_ITEM_FAILURE = "GET_ORDER_ITEM_FAILURE"

export const GET_ORDER_ITEM = "GET_ORDER_ITEM"

export const CREATE_ORDER_ITEM_REQUEST = "CREATE_ORDER_ITEM_REQUEST"
export const CREATE_ORDER_ITEM_SUCCESS = "CREATE_ORDER_ITEM_SUCCESS"
export const CREATE_ORDER_ITEM_FAILURE = "CREATE_ORDER_ITEM_FAILURE"

export const GET_ORDER_TOP_WEEK_REQUEST = "GET_ORDER_TOP_WEEK_REQUEST"
export const GET_ORDER_TOP_WEEK_SUCCESS = "GET_ORDER_TOP_WEEK_SUCCESS"
export const GET_ORDER_TOP_WEEK_FAILURE = "GET_ORDER_TOP_WEEK_FAILURE"

export const GET_ORDER_TOP_MONTH_REQUEST = "GET_ORDER_TOP_MONTH_REQUEST"
export const GET_ORDER_TOP_MONTH_SUCCESS = "GET_ORDER_TOP_MONTH_SUCCESS"
export const GET_ORDER_TOP_MONTH_FAILURE = "GET_ORDER_TOP_MONTH_FAILURE"

export const GET_ORDER_TOP_YEAR_REQUEST = "GET_ORDER_TOP_YEAR_REQUEST"
export const GET_ORDER_TOP_YEAR_SUCCESS = "GET_ORDER_TOP_YEAR_SUCCESS"
export const GET_ORDER_TOP_YEAR_FAILURE = "GET_ORDER_TOP_YEAR_FAILURE"
