export const GET_REVIEW_REQUEST = "GET_REVIEW_REQUEST"
export const GET_REVIEW_SUCCESS = "GET_REVIEW_SUCCESS"
export const GET_REVIEW_FAILURE = "GET_REVIEW_FAILURE"

export const GET_REVIEW_BY_ID_PROCUT_REQUEST = "GET_REVIEW_BY_ID_PROCUT_REQUEST"
export const GET_REVIEW_BY_ID_PROCUT_SUCCESS = "GET_REVIEW_BY_ID_PROCUT_SUCCESS"
export const GET_REVIEW_BY_ID_PROCUT_FAILURE = "GET_REVIEW_BY_ID_PROCUT_FAILURE"

export const GET_REVIEW_BY_RATING_REQUEST = "GET_REVIEW_BY_RATING_REQUEST"
export const GET_REVIEW_BY_RATING_SUCCESS = "GET_REVIEW_BY_RATING_SUCCESS"
export const GET_REVIEW_BY_RATING_FAILURE = "GET_REVIEW_BY_RATING_FAILURE"

export const GET_REVIEW_BY_USER_REQUEST = "GET_REVIEW_BY_USER_REQUEST"
export const GET_REVIEW_BY_USER_SUCCESS = "GET_REVIEW_BY_USER_SUCCESS"
export const GET_REVIEW_BY_USER_FAILURE = "GET_REVIEW_BY_USER_FAILURE"

export const CREATE_REVIEW_REQUEST = "CREATE_REVIEW_REQUEST"
export const CREATE_REVIEW_SUCCESS = "CREATE_REVIEW_SUCCESS"
export const CREATE_REVIEW_FAILURE = "CREATE_REVIEW_FAILURE"

export const CREATE_REVIEW_RESPONSE_REQUEST = "CREATE_REVIEW_RESPONSE_REQUEST"
export const CREATE_REVIEW_RESPONSE_SUCCESS = "CREATE_REVIEW_RESPONSE_SUCCESS"
export const CREATE_REVIEW_RESPONSE_FAILURE = "CREATE_REVIEW_RESPONSE_FAILURE"

