export const FIND_PRODUCT_BY_ID_REQUEST='FIND_PRODUCT_BY_ID_REQUEST'
export const FIND_PRODUCT_BY_ID_SUCCESS='FIND_PRODUCT_BY_ID_SUCCESS'
export const FIND_PRODUCT_BY_ID_FAILURE='FIND_PRODUCT_BY_ID_FAILURE'

export const FIND_PRODUCT_REQUEST='FIND_PRODUCT_BY_CATEGORY_REQUEST'
export const FIND_PRODUCT_SUCCESS='FIND_PRODUCT_BY_CATEGORY_SUCCESS'
export const FIND_PRODUCT_FAILURE='FIND_PRODUCT_BY_CATEGORY_FAILURE'

export const FIND_PRODUCT_BY_CATEGORY_REQUEST='FIND_PRODUCT_BY_CATEGORY_REQUEST'
export const FIND_PRODUCT_BY_CATEGORY_SUCCESS='FIND_PRODUCT_BY_CATEGORY_SUCCESS'
export const FIND_PRODUCT_BY_CATEGORY_FAILURE='FIND_PRODUCT_BY_CATEGORY_FAILURE'


export const GET_PRODUCT_REQUEST = 'GET_PRODUCT_REQUEST'
export const GET_PRODUCT_SUCCESS = 'GET_PRODUCT_SUCCESS'
export const GET_PRODUCT_FAILURE = 'GET_PRODUCT_FAILURE'

export const DELETE_PRODUCT_BY_ID_REQUEST = 'DELETE_PRODUCT_BY_ID_REQUEST'
export const DELETE_PRODUCT_BY_ID_SUCCESS = 'DELETE_PRODUCT_BY_ID_SUCCESS'
export const DELETE_PRODUCT_BY_ID_FAILURE = 'DELETE_PRODUCT_BY_ID_FAILURE'

export const CREATE_PRODUCT_REQUEST = "CREATE_PRODUCT_REQUEST"
export const CREATE_PRODUCT_SUCCESS = "CREATE_PRODUCT_SUCCESS"
export const CREATE_PRODUCT_FAILURE = "CREATE_PRODUCT_FAILURE"

export const GET_PRODUCTS_NEW_BY_CATEGORY_REQUEST = "GET_PRODUCTS_NEW_BY_CATEGORY_REQUEST"
export const GET_PRODUCTS_NEW_BY_CATEGORY_SUCCESS = "GET_PRODUCTS_NEW_BY_CATEGORY_SUCCESS"
export const GET_PRODUCTS_NEW_BY_CATEGORY_FAILURE = "GET_PRODUCTS_NEW_BY_CATEGORY_FAILURE"

export const SORT_PRODUCTS_NEW_REQUEST = "SORT_PRODUCTS_NEW_REQUEST"
export const SORT_PRODUCTS_NEW_SUCCESS = "SORT_PRODUCTS_NEW_SUCCESS"
export const SORT_PRODUCTS_NEW_FAILURE = "SORT_PRODUCTS_NEW_FAILURE"

export const SORT_PRODUCTS_OLD_REQUEST = "SORT_PRODUCTS_OLD_REQUEST"
export const SORT_PRODUCTS_OLD_SUCCESS = "SORT_PRODUCTS_OLD_SUCCESS"
export const SORT_PRODUCTS_OLD_FAILURE = "SORT_PRODUCTS_OLD_FAILURE"

export const SORT_PRODUCTS_LOW_REQUEST = "SORT_PRODUCTS_LOW_REQUEST"
export const SORT_PRODUCTS_LOW_SUCCESS = "SORT_PRODUCTS_LOW_SUCCESS"
export const SORT_PRODUCTS_LOW_FAILURE = "SORT_PRODUCTS_LOW_FAILURE"

export const SORT_PRODUCTS_HIGH_REQUEST = "SORT_PRODUCTS_HIGH_REQUEST"
export const SORT_PRODUCTS_HIGH_SUCCESS = "SORT_PRODUCTS_HIGH_SUCCESS"
export const SORT_PRODUCTS_HIGH_FAILURE = "SORT_PRODUCTS_HIGH_FAILURE"

export const FIND_PRODUCT_FILTER_REQUEST = "FIND_PRODUCT_FILTER_REQUEST"
export const FIND_PRODUCT_FILTER_SUCCESS = "FIND_PRODUCT_FILTER_SUCCESS"
export const FIND_PRODUCT_FILTER_FAILURE = "FIND_PRODUCT_FILTER_FAILURE"

